platform :ios, '8.0'
pod 'Parse'
pod 'ParseUI'
pod 'ParseFacebookUtilsV4'
pod 'ParseCrashReporting'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'DateTools'
# pod 'UIImageEffects'
pod 'FormatterKit'
pod 'IPSqueezableViewController'
pod 'BButton'
pod 'UIImage-ResizeMagick'