platform :ios, '8.0'
pod 'Parse'
pod 'ParseUI'
pod 'ParseFacebookUtilsV4'
pod 'ParseCrashReporting'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
# pod 'AFNetworking', '~>2.5.4'
# pod 'SDWebImage', '~> 3.7.3'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'DateTools'
# pod 'UIImageEffects'
pod 'FormatterKit'
pod 'IPSqueezableViewController'
pod 'BButton'